# Generated by Django 3.1.5 on 2021-02-21 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_payments', to='common.organization')),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.paymenttransaction')),
            ],
        ),
    ]
