# Generated by Django 3.1.5 on 2021-02-21 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_paymenttransaction'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_link', models.TextField(default='')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('price_per_pax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_members', models.IntegerField()),
                ('r_rule', models.TextField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='common.organization')),
            ],
            options={
                'ordering': ['start_time', 'end_time'],
            },
        ),
        migrations.RemoveField(
            model_name='eventpayment',
            name='organization',
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_applications', to='organization.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_applications', to='common.member')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_payments', to='common.organization')),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.paymenttransaction')),
            ],
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='event_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_payments', to='organization.eventapplication'),
        ),
    ]
