# Generated by Django 3.1.5 on 2021-02-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210222_0853'),
        ('organization', '0002_auto_20210221_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionpayment',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_made', to='common.partner'),
        ),
    ]
