# Generated by Django 3.1.5 on 2021-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_contributionpayment_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='r_rule',
        ),
    ]
