# Generated by Django 3.1.5 on 2021-02-23 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210222_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionpayment',
            options={'ordering': ['-expiry_date']},
        ),
        migrations.AddField(
            model_name='contributionpayment',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionpayment',
            name='month_duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
