# Generated by Django 3.1.5 on 2021-03-07 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210223_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionpayment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='contributionpayment',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='contributionpayment',
            name='month_duration',
        ),
        migrations.AddField(
            model_name='contributionpayment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
