# Generated by Django 3.1.7 on 2021-04-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210402_0323'),
        ('organization', '0006_auto_20210307_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionpayment',
            name='payment_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_payment', to='common.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='payment_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_payment', to='common.paymenttransaction'),
        ),
    ]
