# Generated by Django 3.1.6 on 2021-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.TextField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Completed'), ('CLOSED', 'Closed')]),
        ),
    ]
