# Generated by Django 3.1.5 on 2021-02-09 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_auto_20210206_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-timestamp', 'ticket_status', 'ticket_type']},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='base_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.TextField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='OPEN'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='tickets.ticket'),
        ),
    ]
