# Generated by Django 3.1.5 on 2021-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
