# Generated by Django 3.1.5 on 2021-02-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210209_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='common.organization'),
        ),
    ]
