# Generated by Django 3.1.5 on 2021-01-27 08:24

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210125_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=common.models.user_directory_path),
        ),
    ]
