# Generated by Django 3.1.5 on 2021-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_baseuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentprovider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contentprovider',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
