# Generated by Django 3.1.5 on 2021-02-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210209_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
