# Generated by Django 3.1.5 on 2021-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_codeineadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprovider',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
