# Generated by Django 3.1.5 on 2021-02-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_partner_org_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='consultation_rate',
        ),
    ]
