# Generated by Django 3.1.5 on 2021-02-07 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_contentprovider_consultation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprovider',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='industrypartner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_parter', to=settings.AUTH_USER_MODEL),
        ),
    ]
