# Generated by Django 3.1.5 on 2021-02-21 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_partner_consultation_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_status', models.TextField(choices=[('PENDING_COMPLETION', 'Pending Completion'), ('PENDING_REFUND', 'Pending Refund'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING')),
                ('payment_type', models.TextField(choices=[('VISA', 'Visa'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express')])),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
