# Generated by Django 3.1.5 on 2021-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_bankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
