# Generated by Django 3.1.5 on 2021-02-25 10:34

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20210225_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stats',
            field=models.JSONField(default=common.models.get_default_member_stats),
        ),
    ]
