# Generated by Django 3.1.5 on 2021-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_member_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
