# Generated by Django 3.1.5 on 2021-03-06 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_baseuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_tier',
            field=models.TextField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE'),
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_subscriptions', to='common.member')),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.paymenttransaction')),
            ],
        ),
    ]
