# Generated by Django 3.1.5 on 2021-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210306_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='month_duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
