# Generated by Django 3.1.7 on 2021-03-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210307_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipsubscription',
            options={'ordering': ['expiry_date']},
        ),
    ]
