# Generated by Django 3.1.7 on 2021-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210311_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
