# Generated by Django 3.1.7 on 2021-03-13 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='receivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
