# Generated by Django 3.1.7 on 2021-03-30 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.TextField(choices=[('COURSE', 'Course'), ('ARTICLE', 'Article'), ('CODE_REVIEW', 'Code Review'), ('PAYMENT', 'Payment'), ('CONSULTATION', 'Consultation'), ('HELPDESK', 'Helpdesk'), ('INDUSTRY_PROJECTS', 'Industry Project')], default='COURSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
