# Generated by Django 3.1.7 on 2021-04-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210330_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
