# Generated by Django 3.1.7 on 2021-04-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='payment_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_subscription', to='common.paymenttransaction'),
        ),
    ]
