# Generated by Django 3.1.7 on 2021-04-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210402_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-end_date', '-start_date']},
        ),
    ]
