# Generated by Django 3.1.5 on 2021-02-16 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_partner_org_admin'),
        ('community', '0002_auto_20210213_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coding_languages', models.JSONField()),
                ('categories', models.JSONField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to='common.member')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('like', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='community.article')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='common.member')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CodeReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('highlighted_code', models.TextField()),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_review_comments', to='community.codereview')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.codereviewcomment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
