# Generated by Django 3.1.5 on 2021-02-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_codereview_codereviewcomment_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereviewcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='community.codereviewcomment'),
        ),
    ]
