# Generated by Django 3.1.7 on 2021-03-11 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210226_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='coding_languages',
            field=models.JSONField(default={
                "JavaScript": 0,
                "Python": 0
            },),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='languages',
            field=models.JSONField(default={
                "JavaScript": 0,
                "Python": 0
            },),
            preserve_default=False,
        ),
    ]
