# Generated by Django 3.1.7 on 2021-03-13 12:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20210311_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SEC', 'Security'), ('DB', 'Database Administration'), ('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('ML', 'Machine Learning')], max_length=18),
        ),
        migrations.AlterField(
            model_name='article',
            name='coding_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('JS', 'Javascript'), ('CPP', 'C++'), ('CS', 'C#'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('RUBY', 'Ruby')], max_length=31),
        ),
        migrations.AlterField(
            model_name='article',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('MAN', 'Mandarin'), ('FRE', 'French')], max_length=11),
        ),
    ]
