# Generated by Django 3.1.7 on 2021-03-15 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0017_auto_20210313_1308'),
        ('community', '0009_auto_20210313_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engagement',
            new_name='ArticleEngagement',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='display_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.articlecomment'),
        ),
        migrations.CreateModel(
            name='ArticleCommentEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='community.articlecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
