# Generated by Django 3.1.7 on 2021-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20210315_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereviewcomment',
            name='end_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codereviewcomment',
            name='start_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
