# Generated by Django 3.1.7 on 2021-03-15 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20210315_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereviewcomment',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codereviewcomment',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codereviewcomment',
            name='time_edited',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
