# Generated by Django 3.1.7 on 2021-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20210315_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codereviewcomment',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='codereviewcomment',
            name='highlighted_code',
        ),
        migrations.RemoveField(
            model_name='codereviewcomment',
            name='start_index',
        ),
    ]
