# Generated by Django 3.1.7 on 2021-03-18 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0021_cv'),
        ('community', '0014_auto_20210317_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleengagement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_engagements', to='common.member'),
        ),
        migrations.CreateModel(
            name='CodeReviewEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('like', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='community.codereview')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_review_engagements', to='common.member')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CodeReviewCommentEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='community.codereviewcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
