# Generated by Django 3.1.7 on 2021-03-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20210318_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codereviewengagement',
            name='like',
        ),
    ]
