# Generated by Django 3.1.7 on 2021-03-20 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0016_remove_codereviewengagement_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='member',
        ),
        migrations.RemoveField(
            model_name='articleengagement',
            name='member',
        ),
        migrations.RemoveField(
            model_name='codereview',
            name='member',
        ),
        migrations.RemoveField(
            model_name='codereviewengagement',
            name='member',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleengagement',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codereview',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codereviewengagement',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_review_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='time_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
