# Generated by Django 3.1.7 on 2021-03-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20210320_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleengagement',
            name='like',
        ),
    ]
