# Generated by Django 3.1.7 on 2021-03-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_remove_articleengagement_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_edited']},
        ),
    ]
