# Generated by Django 3.1.7 on 2021-04-04 16:21

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20210323_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=community.models.article_directory_path),
        ),
    ]
