# Generated by Django 3.1.7 on 2021-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereviewcomment',
            name='code_line_index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
