# Generated by Django 3.1.5 on 2021-02-03 07:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_contentprovider_consultation_rate'),
        ('courses', '0002_auto_20210202_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.TextField(default='')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('content_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.contentprovider')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.member')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'end_date', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_status', multiselectfield.db.fields.MultiSelectField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=33)),
                ('payment_type', multiselectfield.db.fields.MultiSelectField(choices=[('VISA', 'Visa'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express')], max_length=16)),
                ('consultation_slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='content_provider.consultationslot')),
                ('enrollment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='courses.enrollment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
