# Generated by Django 3.1.5 on 2021-02-09 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.TextField(default='')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.member')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.partner')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'end_date', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_status', models.TextField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING')),
                ('payment_type', models.TextField(choices=[('VISA', 'Visa'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express')])),
                ('consultation_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='consultations.consultationslot')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='courses.enrollment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
