# Generated by Django 3.1.5 on 2021-02-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationslot',
            options={'ordering': ['start_time', 'end_time']},
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
