# Generated by Django 3.1.5 on 2021-02-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_contentprovider_consultation_rate'),
        ('content_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationslot',
            name='content_provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.contentprovider'),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots', to='common.member'),
        ),
    ]
