# Generated by Django 3.1.6 on 2021-02-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_provider', '0003_auto_20210203_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')]),
        ),
    ]
