# Generated by Django 3.1.5 on 2021-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultationslot_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationslot',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
