# Generated by Django 3.1.6 on 2021-02-06 09:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_provider', '0004_auto_20210206_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], max_length=33),
        ),
    ]
