# Generated by Django 3.1.5 on 2021-02-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_partner_org_admin'),
        ('consultations', '0004_consultationslot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='common.partner'),
        ),
    ]
