# Generated by Django 3.1.5 on 2021-02-19 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20210218_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.paymenttransaction')),
            ],
        ),
    ]
