# Generated by Django 3.1.5 on 2021-02-19 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_partner_consultation_rate'),
        ('consultations', '0006_consultationpayment_contributionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationslot',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='member',
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='max_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='price_per_pax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ConsultationApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('consultation_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultationpayment')),
                ('consultation_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_applications', to='consultations.consultationslot')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_applications', to='common.member')),
            ],
        ),
    ]
