# Generated by Django 3.1.6 on 2021-02-06 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_provider', '0006_auto_20210206_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationslot',
            options={'ordering': ['start_date', 'start_time', 'end_date', 'end_time']},
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.TextField(choices=[('VISA', 'Visa'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express')]),
        ),
    ]
