# Generated by Django 3.1.5 on 2021-02-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_auto_20210219_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationapplication',
            name='consultation_payment',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='consultation_slot',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='partner',
        ),
        migrations.AddField(
            model_name='consultationpayment',
            name='consultation_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_payment', to='consultations.consultationslot'),
        ),
    ]
