# Generated by Django 3.1.5 on 2021-02-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_provider', '0007_auto_20210206_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationslot',
            options={'ordering': ['start_time', 'end_time']},
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING'),
        ),
    ]
