# Generated by Django 3.1.5 on 2021-02-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_auto_20210220_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpayment',
            name='consultation_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_payment', to='consultations.consultationapplication'),
        ),
    ]
