# Generated by Django 3.1.5 on 2021-02-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_auto_20210221_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpayment',
            name='consultation_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_payments', to='consultations.consultationapplication'),
        ),
    ]
