# Generated by Django 3.1.5 on 2021-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_auto_20210221_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationslot',
            name='r_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
