# Generated by Django 3.1.5 on 2021-02-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_paymenttransaction'),
        ('consultations', '0012_auto_20210221_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpayment',
            name='payment_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.paymenttransaction'),
        ),
        migrations.DeleteModel(
            name='ContributionPayment',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
