# Generated by Django 3.1.5 on 2021-02-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_auto_20210221_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationslot',
            name='r_rule',
        ),
    ]
