# Generated by Django 3.1.5 on 2021-02-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_remove_consultationslot_r_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationslot',
            name='is_all_day',
        ),
    ]
