# Generated by Django 3.1.7 on 2021-04-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210402_0323'),
        ('consultations', '0015_remove_consultationslot_is_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpayment',
            name='payment_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payment', to='common.paymenttransaction'),
        ),
    ]
