# Generated by Django 3.1.7 on 2021-04-01 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20210323_1702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0003_auto_20210401_0439'),
        ('consultations', '0015_remove_consultationslot_is_all_day'),
        ('common', '0023_delete_notification'),
        ('industry_projects', '0004_industryproject_date_listed'),
        ('courses', '0037_auto_20210323_0719'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='community.article'),
        ),
        migrations.AddField(
            model_name='notification',
            name='code_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='community.codereview'),
        ),
        migrations.AddField(
            model_name='notification',
            name='consultation_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='consultations.consultationslot'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='industry_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='industry_projects.industryproject'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='helpdesk.ticket'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='common.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.TextField(choices=[('GENERAL', 'General'), ('COURSE', 'Course'), ('ARTICLE', 'Article'), ('CODE_REVIEW', 'Code Review'), ('PAYMENT', 'Payment'), ('CONSULTATION', 'Consultation'), ('HELPDESK', 'Helpdesk'), ('INDUSTRY_PROJECTS', 'Industry Project')]),
        ),
        migrations.CreateModel(
            name='NotificationObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_objects', to='notifications.notification')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
