# Generated by Django 3.1.7 on 2021-04-01 05:25

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210401_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=notifications.models.img_directory_path),
        ),
    ]
