# Generated by Django 3.1.7 on 2021-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notificationobject',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='notificationobject',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
