# Generated by Django 3.1.5 on 2021-02-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210222_0853'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_achievements', to='achievements.achievement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='common.member')),
            ],
        ),
    ]
