# Generated by Django 3.1.5 on 2021-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_memberachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementrequirement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='achievementrequirement',
            name='coding_languages',
        ),
        migrations.AddField(
            model_name='achievementrequirement',
            name='stat',
            field=models.CharField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('JS', 'Javascript'), ('CPP', 'C++'), ('CS', 'C#'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('RUBY', 'Ruby'), ('SEC', 'Security'), ('DB', 'Database Administration'), ('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('ML', 'Machine Learning')], default='PY', max_length=255),
            preserve_default=False,
        ),
    ]
