# Generated by Django 3.1.7 on 2021-03-31 04:01

from django.db import migrations, models
import django.db.models.deletion
import helpdesk.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20210323_1702'),
        ('common', '0022_auto_20210330_1012'),
        ('industry_projects', '0004_industryproject_date_listed'),
        ('consultations', '0015_remove_consultationslot_is_all_day'),
        ('courses', '0037_auto_20210323_0719'),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='community.article'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='consultation_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='consultations.consultationslot'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='courses.course'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='industry_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='industry_projects.industryproject'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=helpdesk.models.img_directory_path),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='common.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACCOUNT', 'Account'), ('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('PAYMENT', 'Payments'), ('COURSE', 'Courses'), ('ARTICLE', 'Articles'), ('INDUSTRY_PROJECT', 'Industry Projects'), ('CONSULTATION', 'Consultations')], max_length=78),
        ),
    ]
