# Generated by Django 3.1.7 on 2021-04-01 14:56

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20210401_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=helpdesk.models.file_directory_path),
        ),
    ]
