# Generated by Django 3.1.7 on 2021-04-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_ticketmessage_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
