# Generated by Django 3.1.7 on 2021-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_ticket_assigned_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.TextField(choices=[('ACCOUNT', 'Account'), ('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('PAYMENT', 'Payments'), ('COURSE', 'Courses'), ('ARTICLE', 'Articles'), ('CODE_REVIEWS', 'Code Reviews'), ('INDUSTRY_PROJECT', 'Industry Projects'), ('CONSULTATION', 'Consultations')]),
        ),
    ]
