# Generated by Django 3.1.5 on 2021-02-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210202_1539'),
        ('common', '0006_contentprovider_consultation_rate'),
        ('content_provider', '0002_auto_20210203_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationslot',
            name='content_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_consultation_slots', to='common.contentprovider'),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_consultation_slots', to='common.member'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='consultation_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='content_provider.consultationslot'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='courses.enrollment'),
        ),
    ]
