# Generated by Django 3.1.5 on 2021-02-02 15:00

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_auto_20210127_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('learning_objectives', models.JSONField()),
                ('requirements', models.JSONField()),
                ('description', models.TextField()),
                ('introduction_video_url', models.CharField(max_length=255)),
                ('github_repo', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default=None, null=True, upload_to=courses.models.image_directory_path)),
                ('views', models.PositiveIntegerField()),
                ('coding_languages', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('JS', 'Javascript'), ('CPP', 'C++'), ('CS', 'C#'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('RUBY', 'Ruby')], max_length=31)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('MAN', 'Mandarin'), ('FRE', 'French')], max_length=11)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('SEC', 'Security'), ('DB', 'Database Administration'), ('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('ML', 'Machine Learning')], max_length=18)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('certificate', models.TextField(blank=True, default=None, null=True)),
                ('content_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='common.contentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('video_url', models.CharField(max_length=255)),
                ('google_drive_link', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='common.member')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[courses.models.validate_rating])),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='courses.course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.member')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
    ]
