# Generated by Django 3.1.7 on 2021-04-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videocodesnippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocodesnippet',
            options={'ordering': ['end_time']},
        ),
    ]
