# Generated by Django 3.1.5 on 2021-02-11 07:39

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210211_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='zip_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=courses.models.zipfile_directory_path),
        ),
    ]
