# Generated by Django 3.1.5 on 2021-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='github_repo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction_video_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
