# Generated by Django 3.1.5 on 2021-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210211_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passing_grade',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_marks',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
