# Generated by Django 3.1.5 on 2021-02-06 14:35

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210205_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=courses.models.zipfile_directory_path)),
                ('google_drive_url', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('material_type', models.CharField(choices=[('FILE', 'File'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz')], max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='courses.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField()),
                ('course_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.coursematerial')),
            ],
        ),
        migrations.RemoveField(
            model_name='assessmentanswer',
            name='assessment_result',
        ),
        migrations.RemoveField(
            model_name='assessmentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='member',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='exp_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentAnswer',
        ),
        migrations.DeleteModel(
            name='AssessmentResult',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='coursefile',
            name='course_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_file', to='courses.coursematerial'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_material',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.coursematerial'),
            preserve_default=False,
        ),
    ]
