# Generated by Django 3.1.5 on 2021-02-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210211_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='courses.chapter'),
        ),
    ]
