# Generated by Django 3.1.5 on 2021-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210206_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
