# Generated by Django 3.1.5 on 2021-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210211_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
