# Generated by Django 3.1.5 on 2021-02-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursematerial'),
        ),
    ]
