# Generated by Django 3.1.5 on 2021-02-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exp_points',
        ),
        migrations.AddField(
            model_name='chapter',
            name='exp_points',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
