# Generated by Django 3.1.5 on 2021-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210218_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='chapters_done',
            field=models.JSONField(default=list),
        ),
    ]
