# Generated by Django 3.1.5 on 2021-02-18 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_enrollment_chapters_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
