# Generated by Django 3.1.5 on 2021-02-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210218_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='courses.quizresult'),
        ),
    ]
