# Generated by Django 3.1.5 on 2021-02-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210218_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='total_marks',
            new_name='score',
        ),
    ]
