# Generated by Django 3.1.5 on 2021-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210218_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
