# Generated by Django 3.1.5 on 2021-02-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210218_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='chapters_done',
            new_name='materials_done',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='exp_points',
        ),
    ]
