# Generated by Django 3.1.5 on 2021-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210223_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='exp_points',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
