# Generated by Django 3.1.5 on 2021-02-23 05:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210222_0853'),
        ('courses', '0018_auto_20210223_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to='courses.coursematerial')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_comments', to='common.member')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_comments', to='common.partner')),
            ],
        ),
    ]
