# Generated by Django 3.1.5 on 2021-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursematerial_exp_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='exp_points',
        ),
        migrations.AddField(
            model_name='course',
            name='exp_points',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
