# Generated by Django 3.1.5 on 2021-02-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210223_0654'),
        ('courses', '0019_coursecomment'),
    ]

    operations = [
    ]
