# Generated by Django 3.1.5 on 2021-02-23 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0008_auto_20210222_0853'),
        ('courses', '0021_merge_20210223_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'ordering': ['-pinned']},
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='partner',
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursecomment'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseCommentEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='courses.coursecomment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.member')),
            ],
        ),
    ]
