# Generated by Django 3.1.5 on 2021-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210223_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='display_id',
            field=models.PositiveIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
