# Generated by Django 3.1.5 on 2021-02-24 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_coursecomment_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecommentengagement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
