# Generated by Django 3.1.5 on 2021-03-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_coursecommentengagement_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['is_deleted', 'published_date']},
        ),
    ]
