# Generated by Django 3.1.5 on 2021-03-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20210306_1723'),
        ('courses', '0025_auto_20210307_1557'),
    ]

    operations = [
    ]
