# Generated by Django 3.1.7 on 2021-03-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20210307_0214'),
        ('courses', '0025_auto_20210306_1723'),
    ]

    operations = [
    ]
