# Generated by Django 3.1.7 on 2021-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
