# Generated by Django 3.1.7 on 2021-03-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20210312_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
