# Generated by Django 3.1.7 on 2021-03-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='labels',
            field=models.JSONField(default=dict),
        ),
    ]
