# Generated by Django 3.1.7 on 2021-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210320_0858'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('quiz', 'label'), name='QuestionGroup Unique Constraint: quiz_label'),
        ),
    ]
