# Generated by Django 3.1.7 on 2021-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20210320_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
