# Generated by Django 3.1.7 on 2021-03-23 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20210320_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='questiongroup',
            name='QuestionGroup Unique Constraint: quiz_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='label',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.questionbank'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.questionbank'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('course', 'label'), name='Course_QuestionBank Unique Constraint: label'),
        ),
    ]
