# Generated by Django 3.1.7 on 2021-03-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20210323_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ['order']},
        ),
    ]
