# Generated by Django 3.1.7 on 2021-04-12 14:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('application_deadline', models.DateField(default=None, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('SEC', 'Security'), ('DB', 'Database Administration'), ('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('ML', 'Machine Learning')], default=None, max_length=18, null=True)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_projects', to='common.partner')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryProjectApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('industry_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_project_applications', to='industry_projects.industryproject')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_project_applications', to='common.member')),
            ],
        ),
    ]
