# Generated by Django 3.1.7 on 2021-03-15 08:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industry_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryproject',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SEC', 'Security'), ('DB', 'Database Administration'), ('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('ML', 'Machine Learning')], default=None, max_length=18, null=True),
        ),
    ]
