# Generated by Django 3.1.7 on 2021-03-16 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('industry_projects', '0002_industryproject_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryprojectapplication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
