# Generated by Django 3.1.7 on 2021-03-16 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('industry_projects', '0003_industryprojectapplication_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryproject',
            name='date_listed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 16, 12, 59, 51, 746614, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
