# Generated by Django 3.1.7 on 2021-04-12 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payload', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('search_string', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
