# Generated by Django 3.1.7 on 2021-03-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20210315_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='duration',
            field=models.PositiveBigIntegerField(default=2400),
            preserve_default=False,
        ),
    ]
