# Generated by Django 3.1.7 on 2021-03-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_eventlog_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='search_string',
            field=models.CharField(default='react', max_length=255),
            preserve_default=False,
        ),
    ]
